// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDomainWhoisDomainNameHistoricalParams creates a new GetDomainWhoisDomainNameHistoricalParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDomainWhoisDomainNameHistoricalParams() *GetDomainWhoisDomainNameHistoricalParams {
	return &GetDomainWhoisDomainNameHistoricalParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainWhoisDomainNameHistoricalParamsWithTimeout creates a new GetDomainWhoisDomainNameHistoricalParams object
// with the ability to set a timeout on a request.
func NewGetDomainWhoisDomainNameHistoricalParamsWithTimeout(timeout time.Duration) *GetDomainWhoisDomainNameHistoricalParams {
	return &GetDomainWhoisDomainNameHistoricalParams{
		timeout: timeout,
	}
}

// NewGetDomainWhoisDomainNameHistoricalParamsWithContext creates a new GetDomainWhoisDomainNameHistoricalParams object
// with the ability to set a context for a request.
func NewGetDomainWhoisDomainNameHistoricalParamsWithContext(ctx context.Context) *GetDomainWhoisDomainNameHistoricalParams {
	return &GetDomainWhoisDomainNameHistoricalParams{
		Context: ctx,
	}
}

// NewGetDomainWhoisDomainNameHistoricalParamsWithHTTPClient creates a new GetDomainWhoisDomainNameHistoricalParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDomainWhoisDomainNameHistoricalParamsWithHTTPClient(client *http.Client) *GetDomainWhoisDomainNameHistoricalParams {
	return &GetDomainWhoisDomainNameHistoricalParams{
		HTTPClient: client,
	}
}

/*
GetDomainWhoisDomainNameHistoricalParams contains all the parameters to send to the API endpoint

	for the get domain whois domain name historical operation.

	Typically these are written to a http.Request.
*/
type GetDomainWhoisDomainNameHistoricalParams struct {

	/* DomainName.

	   domain
	*/
	DomainName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get domain whois domain name historical params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDomainWhoisDomainNameHistoricalParams) WithDefaults() *GetDomainWhoisDomainNameHistoricalParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get domain whois domain name historical params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDomainWhoisDomainNameHistoricalParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get domain whois domain name historical params
func (o *GetDomainWhoisDomainNameHistoricalParams) WithTimeout(timeout time.Duration) *GetDomainWhoisDomainNameHistoricalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domain whois domain name historical params
func (o *GetDomainWhoisDomainNameHistoricalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domain whois domain name historical params
func (o *GetDomainWhoisDomainNameHistoricalParams) WithContext(ctx context.Context) *GetDomainWhoisDomainNameHistoricalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domain whois domain name historical params
func (o *GetDomainWhoisDomainNameHistoricalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get domain whois domain name historical params
func (o *GetDomainWhoisDomainNameHistoricalParams) WithHTTPClient(client *http.Client) *GetDomainWhoisDomainNameHistoricalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get domain whois domain name historical params
func (o *GetDomainWhoisDomainNameHistoricalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomainName adds the domainName to the get domain whois domain name historical params
func (o *GetDomainWhoisDomainNameHistoricalParams) WithDomainName(domainName string) *GetDomainWhoisDomainNameHistoricalParams {
	o.SetDomainName(domainName)
	return o
}

// SetDomainName adds the domainName to the get domain whois domain name historical params
func (o *GetDomainWhoisDomainNameHistoricalParams) SetDomainName(domainName string) {
	o.DomainName = domainName
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainWhoisDomainNameHistoricalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param domain-name
	if err := r.SetPathParam("domain-name", o.DomainName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
