// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/cybledev/odin-cli/models"
)

// PostDomainSubdomainCountReader is a Reader for the PostDomainSubdomainCount structure.
type PostDomainSubdomainCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDomainSubdomainCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDomainSubdomainCountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400,402,401:
		result := NewPostDomainSubdomainCountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDomainSubdomainCountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /domain/subdomain/count] PostDomainSubdomainCount", response, response.Code())
	}
}

// NewPostDomainSubdomainCountOK creates a PostDomainSubdomainCountOK with default headers values
func NewPostDomainSubdomainCountOK() *PostDomainSubdomainCountOK {
	return &PostDomainSubdomainCountOK{}
}

/*
PostDomainSubdomainCountOK describes a response with status code 200, with default header values.

OK
*/
type PostDomainSubdomainCountOK struct {
	Payload *PostDomainSubdomainCountOKBody
}

// IsSuccess returns true when this post domain subdomain count o k response has a 2xx status code
func (o *PostDomainSubdomainCountOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post domain subdomain count o k response has a 3xx status code
func (o *PostDomainSubdomainCountOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post domain subdomain count o k response has a 4xx status code
func (o *PostDomainSubdomainCountOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post domain subdomain count o k response has a 5xx status code
func (o *PostDomainSubdomainCountOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post domain subdomain count o k response a status code equal to that given
func (o *PostDomainSubdomainCountOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post domain subdomain count o k response
func (o *PostDomainSubdomainCountOK) Code() int {
	return 200
}

func (o *PostDomainSubdomainCountOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /domain/subdomain/count][%d] postDomainSubdomainCountOK %s", 200, payload)
}

func (o *PostDomainSubdomainCountOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /domain/subdomain/count][%d] postDomainSubdomainCountOK %s", 200, payload)
}

func (o *PostDomainSubdomainCountOK) GetPayload() *PostDomainSubdomainCountOKBody {
	return o.Payload
}

func (o *PostDomainSubdomainCountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostDomainSubdomainCountOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDomainSubdomainCountBadRequest creates a PostDomainSubdomainCountBadRequest with default headers values
func NewPostDomainSubdomainCountBadRequest() *PostDomainSubdomainCountBadRequest {
	return &PostDomainSubdomainCountBadRequest{}
}

/*
PostDomainSubdomainCountBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostDomainSubdomainCountBadRequest struct {
	Payload *models.DNSErrorResponse
}

// IsSuccess returns true when this post domain subdomain count bad request response has a 2xx status code
func (o *PostDomainSubdomainCountBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post domain subdomain count bad request response has a 3xx status code
func (o *PostDomainSubdomainCountBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post domain subdomain count bad request response has a 4xx status code
func (o *PostDomainSubdomainCountBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post domain subdomain count bad request response has a 5xx status code
func (o *PostDomainSubdomainCountBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post domain subdomain count bad request response a status code equal to that given
func (o *PostDomainSubdomainCountBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post domain subdomain count bad request response
func (o *PostDomainSubdomainCountBadRequest) Code() int {
	return 400
}

func (o *PostDomainSubdomainCountBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /domain/subdomain/count][%d] postDomainSubdomainCountBadRequest %s", 400, payload)
}

func (o *PostDomainSubdomainCountBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /domain/subdomain/count][%d] postDomainSubdomainCountBadRequest %s", 400, payload)
}

func (o *PostDomainSubdomainCountBadRequest) GetPayload() *models.DNSErrorResponse {
	return o.Payload
}

func (o *PostDomainSubdomainCountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DNSErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDomainSubdomainCountInternalServerError creates a PostDomainSubdomainCountInternalServerError with default headers values
func NewPostDomainSubdomainCountInternalServerError() *PostDomainSubdomainCountInternalServerError {
	return &PostDomainSubdomainCountInternalServerError{}
}

/*
PostDomainSubdomainCountInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostDomainSubdomainCountInternalServerError struct {
	Payload *models.DNSErrorResponse
}

// IsSuccess returns true when this post domain subdomain count internal server error response has a 2xx status code
func (o *PostDomainSubdomainCountInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post domain subdomain count internal server error response has a 3xx status code
func (o *PostDomainSubdomainCountInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post domain subdomain count internal server error response has a 4xx status code
func (o *PostDomainSubdomainCountInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post domain subdomain count internal server error response has a 5xx status code
func (o *PostDomainSubdomainCountInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post domain subdomain count internal server error response a status code equal to that given
func (o *PostDomainSubdomainCountInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post domain subdomain count internal server error response
func (o *PostDomainSubdomainCountInternalServerError) Code() int {
	return 500
}

func (o *PostDomainSubdomainCountInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /domain/subdomain/count][%d] postDomainSubdomainCountInternalServerError %s", 500, payload)
}

func (o *PostDomainSubdomainCountInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /domain/subdomain/count][%d] postDomainSubdomainCountInternalServerError %s", 500, payload)
}

func (o *PostDomainSubdomainCountInternalServerError) GetPayload() *models.DNSErrorResponse {
	return o.Payload
}

func (o *PostDomainSubdomainCountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DNSErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PostDomainSubdomainCountOKBody post domain subdomain count o k body
swagger:model PostDomainSubdomainCountOKBody
*/
type PostDomainSubdomainCountOKBody struct {
	models.DNSAPIResponse

	// data
	Data *models.DNSData `json:"data,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostDomainSubdomainCountOKBody) UnmarshalJSON(raw []byte) error {
	// PostDomainSubdomainCountOKBodyAO0
	var postDomainSubdomainCountOKBodyAO0 models.DNSAPIResponse
	if err := swag.ReadJSON(raw, &postDomainSubdomainCountOKBodyAO0); err != nil {
		return err
	}
	o.DNSAPIResponse = postDomainSubdomainCountOKBodyAO0

	// PostDomainSubdomainCountOKBodyAO1
	var dataPostDomainSubdomainCountOKBodyAO1 struct {
		Data *models.DNSData `json:"data,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPostDomainSubdomainCountOKBodyAO1); err != nil {
		return err
	}

	o.Data = dataPostDomainSubdomainCountOKBodyAO1.Data

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostDomainSubdomainCountOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	postDomainSubdomainCountOKBodyAO0, err := swag.WriteJSON(o.DNSAPIResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postDomainSubdomainCountOKBodyAO0)
	var dataPostDomainSubdomainCountOKBodyAO1 struct {
		Data *models.DNSData `json:"data,omitempty"`
	}

	dataPostDomainSubdomainCountOKBodyAO1.Data = o.Data

	jsonDataPostDomainSubdomainCountOKBodyAO1, errPostDomainSubdomainCountOKBodyAO1 := swag.WriteJSON(dataPostDomainSubdomainCountOKBodyAO1)
	if errPostDomainSubdomainCountOKBodyAO1 != nil {
		return nil, errPostDomainSubdomainCountOKBodyAO1
	}
	_parts = append(_parts, jsonDataPostDomainSubdomainCountOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post domain subdomain count o k body
func (o *PostDomainSubdomainCountOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.DNSAPIResponse
	if err := o.DNSAPIResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostDomainSubdomainCountOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postDomainSubdomainCountOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postDomainSubdomainCountOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post domain subdomain count o k body based on the context it is used
func (o *PostDomainSubdomainCountOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.DNSAPIResponse
	if err := o.DNSAPIResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostDomainSubdomainCountOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if swag.IsZero(o.Data) { // not required
			return nil
		}

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postDomainSubdomainCountOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postDomainSubdomainCountOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostDomainSubdomainCountOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostDomainSubdomainCountOKBody) UnmarshalBinary(b []byte) error {
	var res PostDomainSubdomainCountOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
