// Code generated by go-swagger; DO NOT EDIT.

package dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-cli/models"
)

// NewPostDomainSearchParams creates a new PostDomainSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDomainSearchParams() *PostDomainSearchParams {
	return &PostDomainSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDomainSearchParamsWithTimeout creates a new PostDomainSearchParams object
// with the ability to set a timeout on a request.
func NewPostDomainSearchParamsWithTimeout(timeout time.Duration) *PostDomainSearchParams {
	return &PostDomainSearchParams{
		timeout: timeout,
	}
}

// NewPostDomainSearchParamsWithContext creates a new PostDomainSearchParams object
// with the ability to set a context for a request.
func NewPostDomainSearchParamsWithContext(ctx context.Context) *PostDomainSearchParams {
	return &PostDomainSearchParams{
		Context: ctx,
	}
}

// NewPostDomainSearchParamsWithHTTPClient creates a new PostDomainSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDomainSearchParamsWithHTTPClient(client *http.Client) *PostDomainSearchParams {
	return &PostDomainSearchParams{
		HTTPClient: client,
	}
}

/*
PostDomainSearchParams contains all the parameters to send to the API endpoint

	for the post domain search operation.

	Typically these are written to a http.Request.
*/
type PostDomainSearchParams struct {

	/* Query.

	   Query
	*/
	Query *models.DNSDomainRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post domain search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDomainSearchParams) WithDefaults() *PostDomainSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post domain search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDomainSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post domain search params
func (o *PostDomainSearchParams) WithTimeout(timeout time.Duration) *PostDomainSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post domain search params
func (o *PostDomainSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post domain search params
func (o *PostDomainSearchParams) WithContext(ctx context.Context) *PostDomainSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post domain search params
func (o *PostDomainSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post domain search params
func (o *PostDomainSearchParams) WithHTTPClient(client *http.Client) *PostDomainSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post domain search params
func (o *PostDomainSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post domain search params
func (o *PostDomainSearchParams) WithQuery(query *models.DNSDomainRequest) *PostDomainSearchParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post domain search params
func (o *PostDomainSearchParams) SetQuery(query *models.DNSDomainRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostDomainSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
