// Code generated by go-swagger; DO NOT EDIT.

package credits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCreditsUsageParams creates a new GetCreditsUsageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCreditsUsageParams() *GetCreditsUsageParams {
	return &GetCreditsUsageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCreditsUsageParamsWithTimeout creates a new GetCreditsUsageParams object
// with the ability to set a timeout on a request.
func NewGetCreditsUsageParamsWithTimeout(timeout time.Duration) *GetCreditsUsageParams {
	return &GetCreditsUsageParams{
		timeout: timeout,
	}
}

// NewGetCreditsUsageParamsWithContext creates a new GetCreditsUsageParams object
// with the ability to set a context for a request.
func NewGetCreditsUsageParamsWithContext(ctx context.Context) *GetCreditsUsageParams {
	return &GetCreditsUsageParams{
		Context: ctx,
	}
}

// NewGetCreditsUsageParamsWithHTTPClient creates a new GetCreditsUsageParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCreditsUsageParamsWithHTTPClient(client *http.Client) *GetCreditsUsageParams {
	return &GetCreditsUsageParams{
		HTTPClient: client,
	}
}

/*
GetCreditsUsageParams contains all the parameters to send to the API endpoint

	for the get credits usage operation.

	Typically these are written to a http.Request.
*/
type GetCreditsUsageParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get credits usage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCreditsUsageParams) WithDefaults() *GetCreditsUsageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get credits usage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCreditsUsageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get credits usage params
func (o *GetCreditsUsageParams) WithTimeout(timeout time.Duration) *GetCreditsUsageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get credits usage params
func (o *GetCreditsUsageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get credits usage params
func (o *GetCreditsUsageParams) WithContext(ctx context.Context) *GetCreditsUsageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get credits usage params
func (o *GetCreditsUsageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get credits usage params
func (o *GetCreditsUsageParams) WithHTTPClient(client *http.Client) *GetCreditsUsageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get credits usage params
func (o *GetCreditsUsageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCreditsUsageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
