// Code generated by go-swagger; DO NOT EDIT.

package hosts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-cli/models"
)

// NewPostV2HostsCountParams creates a new PostV2HostsCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV2HostsCountParams() *PostV2HostsCountParams {
	return &PostV2HostsCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV2HostsCountParamsWithTimeout creates a new PostV2HostsCountParams object
// with the ability to set a timeout on a request.
func NewPostV2HostsCountParamsWithTimeout(timeout time.Duration) *PostV2HostsCountParams {
	return &PostV2HostsCountParams{
		timeout: timeout,
	}
}

// NewPostV2HostsCountParamsWithContext creates a new PostV2HostsCountParams object
// with the ability to set a context for a request.
func NewPostV2HostsCountParamsWithContext(ctx context.Context) *PostV2HostsCountParams {
	return &PostV2HostsCountParams{
		Context: ctx,
	}
}

// NewPostV2HostsCountParamsWithHTTPClient creates a new PostV2HostsCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV2HostsCountParamsWithHTTPClient(client *http.Client) *PostV2HostsCountParams {
	return &PostV2HostsCountParams{
		HTTPClient: client,
	}
}

/*
PostV2HostsCountParams contains all the parameters to send to the API endpoint

	for the post v2 hosts count operation.

	Typically these are written to a http.Request.
*/
type PostV2HostsCountParams struct {

	/* Query.

	   Count Query
	*/
	Query *models.CybleComOdinAPIControllersV2IpservicesCountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v2 hosts count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV2HostsCountParams) WithDefaults() *PostV2HostsCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v2 hosts count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV2HostsCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v2 hosts count params
func (o *PostV2HostsCountParams) WithTimeout(timeout time.Duration) *PostV2HostsCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v2 hosts count params
func (o *PostV2HostsCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v2 hosts count params
func (o *PostV2HostsCountParams) WithContext(ctx context.Context) *PostV2HostsCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v2 hosts count params
func (o *PostV2HostsCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v2 hosts count params
func (o *PostV2HostsCountParams) WithHTTPClient(client *http.Client) *PostV2HostsCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v2 hosts count params
func (o *PostV2HostsCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post v2 hosts count params
func (o *PostV2HostsCountParams) WithQuery(query *models.CybleComOdinAPIControllersV2IpservicesCountRequest) *PostV2HostsCountParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post v2 hosts count params
func (o *PostV2HostsCountParams) SetQuery(query *models.CybleComOdinAPIControllersV2IpservicesCountRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostV2HostsCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
