// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/cybledev/odin-cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for CountRequest

// register flags to command
func registerModelCountRequestFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerCountRequestPropQuery(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerCountRequestPropQuery(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagQueryDescription := ``

	var flagQueryName string
	if cmdPrefix == "" {
		flagQueryName = "query"
	} else {
		flagQueryName = fmt.Sprintf("%v.query", cmdPrefix)
	}

	var flagQueryDefault string

	_ = cmd.PersistentFlags().String(flagQueryName, flagQueryDefault, flagQueryDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelCountRequestFlags(depth int, m *models.CountRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, QueryAdded := retrieveCountRequestPropQueryFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || QueryAdded

	return nil, retAdded
}

func retrieveCountRequestPropQueryFlags(depth int, m *models.CountRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagQueryName := fmt.Sprintf("%v.query", cmdPrefix)
	if cmd.Flags().Changed(flagQueryName) {

		var flagQueryName string
		if cmdPrefix == "" {
			flagQueryName = "query"
		} else {
			flagQueryName = fmt.Sprintf("%v.query", cmdPrefix)
		}

		flagQueryValue, err := cmd.Flags().GetString(flagQueryName)
		if err != nil {
			return err, false
		}
		m.Query = flagQueryValue

		retAdded = true
	}

	return nil, retAdded
}
