// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/cybledev/odin-cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for CybleComOdinAPIControllersV2IpservicesSummaryRequest

// register flags to command
func registerModelCybleComOdinAPIControllersV2IpservicesSummaryRequestFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerCybleComOdinAPIControllersV2IpservicesSummaryRequestPropField(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCybleComOdinAPIControllersV2IpservicesSummaryRequestPropLimit(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerCybleComOdinAPIControllersV2IpservicesSummaryRequestPropQuery(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerCybleComOdinAPIControllersV2IpservicesSummaryRequestPropField(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagFieldDescription := `Required. `

	var flagFieldName string
	if cmdPrefix == "" {
		flagFieldName = "field"
	} else {
		flagFieldName = fmt.Sprintf("%v.field", cmdPrefix)
	}

	var flagFieldDefault string

	_ = cmd.PersistentFlags().String(flagFieldName, flagFieldDefault, flagFieldDescription)

	return nil
}

func registerCybleComOdinAPIControllersV2IpservicesSummaryRequestPropLimit(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagLimitDescription := `(default 1) `

	var flagLimitName string
	if cmdPrefix == "" {
		flagLimitName = "limit"
	} else {
		flagLimitName = fmt.Sprintf("%v.limit", cmdPrefix)
	}

	var flagLimitDefault int64

	_ = cmd.PersistentFlags().Int64(flagLimitName, flagLimitDefault, flagLimitDescription)

	return nil
}

func registerCybleComOdinAPIControllersV2IpservicesSummaryRequestPropQuery(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagQueryDescription := `(default *) `

	var flagQueryName string
	if cmdPrefix == "" {
		flagQueryName = "query"
	} else {
		flagQueryName = fmt.Sprintf("%v.query", cmdPrefix)
	}

	var flagQueryDefault string = defaultQuery

	_ = cmd.PersistentFlags().String(flagQueryName, flagQueryDefault, flagQueryDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelCybleComOdinAPIControllersV2IpservicesSummaryRequestFlags(depth int, m *models.CybleComOdinAPIControllersV2IpservicesSummaryRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, FieldAdded := retrieveCybleComOdinAPIControllersV2IpservicesSummaryRequestPropFieldFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || FieldAdded

	err, LimitAdded := retrieveCybleComOdinAPIControllersV2IpservicesSummaryRequestPropLimitFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || LimitAdded

	err, QueryAdded := retrieveCybleComOdinAPIControllersV2IpservicesSummaryRequestPropQueryFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || QueryAdded

	return nil, retAdded
}

func retrieveCybleComOdinAPIControllersV2IpservicesSummaryRequestPropFieldFlags(depth int, m *models.CybleComOdinAPIControllersV2IpservicesSummaryRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagFieldName := fmt.Sprintf("%v.field", cmdPrefix)
	if cmd.Flags().Changed(flagFieldName) {

		var flagFieldName string
		if cmdPrefix == "" {
			flagFieldName = "field"
		} else {
			flagFieldName = fmt.Sprintf("%v.field", cmdPrefix)
		}

		flagFieldValue, err := cmd.Flags().GetString(flagFieldName)
		if err != nil {
			return err, false
		}
		m.Field = &flagFieldValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveCybleComOdinAPIControllersV2IpservicesSummaryRequestPropLimitFlags(depth int, m *models.CybleComOdinAPIControllersV2IpservicesSummaryRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagLimitName := fmt.Sprintf("%v.limit", cmdPrefix)
	if cmd.Flags().Changed(flagLimitName) {

		var flagLimitName string
		if cmdPrefix == "" {
			flagLimitName = "limit"
		} else {
			flagLimitName = fmt.Sprintf("%v.limit", cmdPrefix)
		}

		flagLimitValue, err := cmd.Flags().GetInt64(flagLimitName)
		if err != nil {
			return err, false
		}
		m.Limit = &flagLimitValue

		retAdded = true
	} else {
		retAdded = true
		m.Limit = defaultLimit
	}

	return nil, retAdded
}

func retrieveCybleComOdinAPIControllersV2IpservicesSummaryRequestPropQueryFlags(depth int, m *models.CybleComOdinAPIControllersV2IpservicesSummaryRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagQueryName := fmt.Sprintf("%v.query", cmdPrefix)
	if cmd.Flags().Changed(flagQueryName) {

		var flagQueryName string
		if cmdPrefix == "" {
			flagQueryName = "query"
		} else {
			flagQueryName = fmt.Sprintf("%v.query", cmdPrefix)
		}

		flagQueryValue, err := cmd.Flags().GetString(flagQueryName)
		if err != nil {
			return err, false
		}
		m.Query = flagQueryValue

		retAdded = true
	}

	return nil, retAdded
}
