// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/cybledev/odin-cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for FieldsField

// register flags to command
func registerModelFieldsFieldFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerFieldsFieldPropCategory(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerFieldsFieldPropDisplayCategory(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerFieldsFieldPropName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerFieldsFieldPropCategory(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagCategoryDescription := ``

	var flagCategoryName string
	if cmdPrefix == "" {
		flagCategoryName = "category"
	} else {
		flagCategoryName = fmt.Sprintf("%v.category", cmdPrefix)
	}

	var flagCategoryDefault string

	_ = cmd.PersistentFlags().String(flagCategoryName, flagCategoryDefault, flagCategoryDescription)

	return nil
}

func registerFieldsFieldPropDisplayCategory(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagDisplayCategoryDescription := ``

	var flagDisplayCategoryName string
	if cmdPrefix == "" {
		flagDisplayCategoryName = "display_category"
	} else {
		flagDisplayCategoryName = fmt.Sprintf("%v.display_category", cmdPrefix)
	}

	var flagDisplayCategoryDefault string

	_ = cmd.PersistentFlags().String(flagDisplayCategoryName, flagDisplayCategoryDefault, flagDisplayCategoryDescription)

	return nil
}

func registerFieldsFieldPropName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagNameDescription := ``

	var flagNameName string
	if cmdPrefix == "" {
		flagNameName = "name"
	} else {
		flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var flagNameDefault string

	_ = cmd.PersistentFlags().String(flagNameName, flagNameDefault, flagNameDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelFieldsFieldFlags(depth int, m *models.FieldsField, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, CategoryAdded := retrieveFieldsFieldPropCategoryFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || CategoryAdded

	err, DisplayCategoryAdded := retrieveFieldsFieldPropDisplayCategoryFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DisplayCategoryAdded

	err, NameAdded := retrieveFieldsFieldPropNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || NameAdded

	return nil, retAdded
}

func retrieveFieldsFieldPropCategoryFlags(depth int, m *models.FieldsField, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagCategoryName := fmt.Sprintf("%v.category", cmdPrefix)
	if cmd.Flags().Changed(flagCategoryName) {

		var flagCategoryName string
		if cmdPrefix == "" {
			flagCategoryName = "category"
		} else {
			flagCategoryName = fmt.Sprintf("%v.category", cmdPrefix)
		}

		flagCategoryValue, err := cmd.Flags().GetString(flagCategoryName)
		if err != nil {
			return err, false
		}
		m.Category = flagCategoryValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveFieldsFieldPropDisplayCategoryFlags(depth int, m *models.FieldsField, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDisplayCategoryName := fmt.Sprintf("%v.display_category", cmdPrefix)
	if cmd.Flags().Changed(flagDisplayCategoryName) {

		var flagDisplayCategoryName string
		if cmdPrefix == "" {
			flagDisplayCategoryName = "display_category"
		} else {
			flagDisplayCategoryName = fmt.Sprintf("%v.display_category", cmdPrefix)
		}

		flagDisplayCategoryValue, err := cmd.Flags().GetString(flagDisplayCategoryName)
		if err != nil {
			return err, false
		}
		m.DisplayCategory = flagDisplayCategoryValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveFieldsFieldPropNameFlags(depth int, m *models.FieldsField, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagNameName := fmt.Sprintf("%v.name", cmdPrefix)
	if cmd.Flags().Changed(flagNameName) {

		var flagNameName string
		if cmdPrefix == "" {
			flagNameName = "name"
		} else {
			flagNameName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		flagNameValue, err := cmd.Flags().GetString(flagNameName)
		if err != nil {
			return err, false
		}
		m.Name = flagNameValue

		retAdded = true
	}

	return nil, retAdded
}
