// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/cybledev/odin-cli/odin_cli/health"

	"github.com/cybledev/odin-cli/decorator"
	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationHealthGetPingCmd returns a command to handle operation getPing
func makeOperationHealthGetPingCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Args:  cobra.NoArgs,
		Use:   "ping",
		Short: `Returns the pong as response`,
		RunE:   decorator.RunEColorWrapper(runOperationHealthGetPing),
	}

	if err := registerOperationHealthGetPingParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationHealthGetPing uses cmd flags to call endpoint api
func runOperationHealthGetPing(cmd *cobra.Command, args []string) (string, error) {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return "", err
	}
	// retrieve flag values from cmd and fill params
	params := health.NewGetPingParams()
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return "", nil
	}
	// make request and then print result
	msgStr, err := parseOperationHealthGetPingResult(appCli.Health.GetPing(params))
	if err != nil {
		return "", err
	}

	if !debug {
		return msgStr, nil
	}

	return "", nil
}

// registerOperationHealthGetPingParamFlags registers all flags needed to fill params
func registerOperationHealthGetPingParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationHealthGetPingResult parses request result and return the string content
func parseOperationHealthGetPingResult(resp0 *health.GetPingOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*health.GetPingOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr := fmt.Sprintf("%v", resp0.Payload)
		return string(msgStr), nil
	}

	return "", nil
}
