// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/cybledev/odin-cli/decorator"
	"github.com/cybledev/odin-cli/models"
	"github.com/cybledev/odin-cli/odin_cli/dns"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredCmd returns a command to handle operation getDomainWhoisDomainNameIsRegistered
func makeOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "whois-is-registered",
		Short: `Provides info if the domain is registered or not`,
		RunE:  decorator.RunEColorWrapper(runOperationDomainWhoisGetDomainWhoisDomainNameIsRegistered),
	}

	if err := registerOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDomainWhoisGetDomainWhoisDomainNameIsRegistered uses cmd flags to call endpoint api
func runOperationDomainWhoisGetDomainWhoisDomainNameIsRegistered(cmd *cobra.Command, args []string) (string, error) {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return "", err
	}
	// retrieve flag values from cmd and fill params
	params := dns.NewGetDomainWhoisDomainNameIsRegisteredParams()
	if err, _ = retrieveOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredDomainNameFlag(params, "", cmd); err != nil {
		return "", err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return "", nil
	}
	// make request and then print result
	msgStr, err := parseOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredResult(appCli.DNS.GetDomainWhoisDomainNameIsRegistered(params, nil))
	if err != nil {
		return "", err
	}

	if !debug {
		return msgStr, nil
	}
	return "", nil
}

// registerOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredParamFlags registers all flags needed to fill params
func registerOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredParamFlags(cmd *cobra.Command) error {
	if err := registerOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredDomainNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredDomainNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagDomainNameDescription := `Required. domain`

	var flagDomainNameName string
	if cmdPrefix == "" {
		flagDomainNameName = "domain-name"
	} else {
		flagDomainNameName = fmt.Sprintf("%v.domain-name", cmdPrefix)
	}

	var flagDomainNameDefault string

	_ = cmd.PersistentFlags().String(flagDomainNameName, flagDomainNameDefault, flagDomainNameDescription)

	return nil
}

func retrieveOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredDomainNameFlag(m *dns.GetDomainWhoisDomainNameIsRegisteredParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("domain-name") {

		var flagDomainNameName string
		if cmdPrefix == "" {
			flagDomainNameName = "domain-name"
		} else {
			flagDomainNameName = fmt.Sprintf("%v.domain-name", cmdPrefix)
		}

		flagDomainNameValue, err := cmd.Flags().GetString(flagDomainNameName)
		if err != nil {
			return err, false
		}
		m.DomainName = flagDomainNameValue

	}

	return nil, retAdded
}

// parseOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredResult parses request result and return the string content
func parseOperationDomainWhoisGetDomainWhoisDomainNameIsRegisteredResult(resp0 *dns.GetDomainWhoisDomainNameIsRegisteredOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*dns.GetDomainWhoisDomainNameIsRegisteredOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*dns.GetDomainWhoisDomainNameIsRegisteredBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*dns.GetDomainWhoisDomainNameIsRegisteredPaymentRequired)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*dns.GetDomainWhoisDomainNameIsRegisteredRequestTimeout)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*dns.GetDomainWhoisDomainNameIsRegisteredInternalServerError)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelGetDomainWhoisDomainNameIsRegisteredOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded models.SchemaAPIResponse flags

	if err := registerModelSchemaAPIResponseFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	// register anonymous fields for getDomainWhoisDomainNameIsRegisteredOKBodyAO1

	if err := registerGetDomainWhoisDomainNameIsRegisteredOKBodyPropAnonGetDomainWhoisDomainNameIsRegisteredOKBodyAO1Data(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerGetDomainWhoisDomainNameIsRegisteredOKBodyPropAnonGetDomainWhoisDomainNameIsRegisteredOKBodyAO1Meta(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

// inline definition name getDomainWhoisDomainNameIsRegisteredOKBodyAO1, type

func registerGetDomainWhoisDomainNameIsRegisteredOKBodyPropAnonGetDomainWhoisDomainNameIsRegisteredOKBodyAO1Data(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: data []*models.SchemaDomainWhoisResponse array type is not supported by go-swagger cli yet

	return nil
}

func registerGetDomainWhoisDomainNameIsRegisteredOKBodyPropAnonGetDomainWhoisDomainNameIsRegisteredOKBodyAO1Meta(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagMetaName string
	if cmdPrefix == "" {
		flagMetaName = "meta"
	} else {
		flagMetaName = fmt.Sprintf("%v.meta", cmdPrefix)
	}

	if err := registerModelSchemaPaginationMetaFlags(depth+1, flagMetaName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelGetDomainWhoisDomainNameIsRegisteredOKBodyFlags(depth int, m *dns.GetDomainWhoisDomainNameIsRegisteredOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model models.SchemaAPIResponse
	err, GetDomainWhoisDomainNameIsRegisteredOKBodyAO0Added := retrieveModelSchemaAPIResponseFlags(depth, &m.SchemaAPIResponse, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || GetDomainWhoisDomainNameIsRegisteredOKBodyAO0Added

	// retrieve allOf getDomainWhoisDomainNameIsRegisteredOKBodyAO1 fields

	err, DataAdded := retrieveGetDomainWhoisDomainNameIsRegisteredOKBodyPropAnonGetDomainWhoisDomainNameIsRegisteredOKBodyAO1DataFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DataAdded

	err, MetaAdded := retrieveGetDomainWhoisDomainNameIsRegisteredOKBodyPropAnonGetDomainWhoisDomainNameIsRegisteredOKBodyAO1MetaFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MetaAdded

	return nil, retAdded
}

// define retrieve functions for fields for inline definition name getDomainWhoisDomainNameIsRegisteredOKBodyAO1

func retrieveGetDomainWhoisDomainNameIsRegisteredOKBodyPropAnonGetDomainWhoisDomainNameIsRegisteredOKBodyAO1DataFlags(depth int, m *dns.GetDomainWhoisDomainNameIsRegisteredOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDataName := fmt.Sprintf("%v.data", cmdPrefix)
	if cmd.Flags().Changed(flagDataName) {
		// warning: data array type []*models.SchemaDomainWhoisResponse is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveGetDomainWhoisDomainNameIsRegisteredOKBodyPropAnonGetDomainWhoisDomainNameIsRegisteredOKBodyAO1MetaFlags(depth int, m *dns.GetDomainWhoisDomainNameIsRegisteredOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagMetaName := fmt.Sprintf("%v.meta", cmdPrefix)
	if cmd.Flags().Changed(flagMetaName) {
		// info: complex object meta models.SchemaPaginationMeta is retrieved outside this Changed() block
	}
	flagMetaValue := m.Meta
	if swag.IsZero(flagMetaValue) {
		flagMetaValue = &models.SchemaPaginationMeta{}
	}

	err, MetaAdded := retrieveModelSchemaPaginationMetaFlags(depth+1, flagMetaValue, flagMetaName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || MetaAdded
	if MetaAdded {
		m.Meta = flagMetaValue
	}

	return nil, retAdded
}
