// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/cybledev/odin-cli/decorator"
	"github.com/cybledev/odin-cli/odin_cli/hosts"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationHostsPostV2HostsIPCmd returns a command to handle operation postV2HostsIp
func makeOperationHostsPostV2HostsIPCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "v2-hosts-ip",
		Short: `Returns the complete ip details`,
		RunE:  decorator.RunEColorWrapper(runOperationHostsPostV2HostsIP),
	}

	if err := registerOperationHostsPostV2HostsIPParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationHostsPostV2HostsIP uses cmd flags to call endpoint api
func runOperationHostsPostV2HostsIP(cmd *cobra.Command, args []string) (string, error) {
	args = append(args, apiVersionPrefix + "/v2/")
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return "", err
	}
	// retrieve flag values from cmd and fill params
	params := hosts.NewPostV2HostsIPParams()
	if err, _ = retrieveOperationHostsPostV2HostsIPIPFlag(params, "", cmd); err != nil {
		return "", err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return "", nil
	}
	// make request and then print result
	msgStr, err := parseOperationHostsPostV2HostsIPResult(appCli.Hosts.PostV2HostsIP(params, nil))
	if err != nil {
		return "", err
	}

	if !debug {
		return msgStr, nil
	}

	return "", nil
}

// registerOperationHostsPostV2HostsIPParamFlags registers all flags needed to fill params
func registerOperationHostsPostV2HostsIPParamFlags(cmd *cobra.Command) error {
	if err := registerOperationHostsPostV2HostsIPIPParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationHostsPostV2HostsIPIPParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	flagIPDescription := `Required. get the ip`

	var flagIPName string
	if cmdPrefix == "" {
		flagIPName = "ip"
	} else {
		flagIPName = fmt.Sprintf("%v.ip", cmdPrefix)
	}

	var flagIPDefault string

	_ = cmd.PersistentFlags().String(flagIPName, flagIPDefault, flagIPDescription)

	return nil
}

func retrieveOperationHostsPostV2HostsIPIPFlag(m *hosts.PostV2HostsIPParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("ip") {

		var flagIPName string
		if cmdPrefix == "" {
			flagIPName = "ip"
		} else {
			flagIPName = fmt.Sprintf("%v.ip", cmdPrefix)
		}

		flagIPValue, err := cmd.Flags().GetString(flagIPName)
		if err != nil {
			return err, false
		}
		m.IP = flagIPValue

	}

	return nil, retAdded
}

// parseOperationHostsPostV2HostsIPResult parses request result and return the string content
func parseOperationHostsPostV2HostsIPResult(resp0 *hosts.PostV2HostsIPOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*hosts.PostV2HostsIPOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*hosts.PostV2HostsIPBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*hosts.PostV2HostsIPPaymentRequired)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*hosts.PostV2HostsIPRequestTimeout)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp4 interface{} = respErr
		resp4, ok := iResp4.(*hosts.PostV2HostsIPInternalServerError)
		if ok {
			if !swag.IsZero(resp4) && !swag.IsZero(resp4.Payload) {
				msgStr, err := json.Marshal(resp4.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
