// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/cybledev/odin-cli/models"
	"github.com/cybledev/odin-cli/odin_cli/dns"

	"github.com/cybledev/odin-cli/decorator"
	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDNSPostDNSSearchCmd returns a command to handle operation postDnsSearch
func makeOperationDNSPostDNSSearchCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Args: cobra.NoArgs,
		Use:   "search",
		Short: `Returns the subdomain records based on query`,
		RunE:  decorator.RunEColorWrapper(runOperationDNSPostDNSSearch),
	}

	if err := registerOperationDNSPostDNSSearchParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDNSPostDNSSearch uses cmd flags to call endpoint api
func runOperationDNSPostDNSSearch(cmd *cobra.Command, args []string) (string, error) {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return "", err
	}
	// retrieve flag values from cmd and fill params
	params := dns.NewPostDomainSearchParams()
	if err, _ = retrieveOperationDNSPostDomainSearchQueryFlag(params, "", cmd); err != nil {
		return "", err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return "", nil
	}
	// make request and then print result
	msgStr, err := parseOperationDNSPostDomainSearchResult(appCli.DNS.PostDomainSearch(params, nil))
	if err != nil {
		return "", err
	}

	if !debug {
		return msgStr, nil
	}

	return "", nil
}

// registerOperationDNSPostDNSSearchParamFlags registers all flags needed to fill params
func registerOperationDNSPostDNSSearchParamFlags(cmd *cobra.Command) error {
	if err := registerOperationDNSPostDNSSearchQueryParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationDNSPostDNSSearchQueryParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagQueryName string
	if cmdPrefix == "" {
		flagQueryName = "query"
	} else {
		flagQueryName = fmt.Sprintf("%v.query", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagQueryName, "", `Optional json string for [query]. Query`)

	// add flags for body
	if err := registerModelDNSDomainRequestFlags(0, "request", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationDNSPostDNSSearchQueryFlag(m *dns.PostDomainSearchParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("query") {
		// Read query string from cmd and unmarshal
		flagQueryValueStr, err := cmd.Flags().GetString("query")
		if err != nil {
			return err, false
		}

		flagQueryValue := models.DNSDomainRequest{}
		if err := json.Unmarshal([]byte(flagQueryValueStr), &flagQueryValue); err != nil {
			return fmt.Errorf("cannot unmarshal query string in models.DNSDNSRequest: %v", err), false
		}
		m.Query = &flagQueryValue
	}
	flagQueryModel := m.Query
	if swag.IsZero(flagQueryModel) {
		flagQueryModel = &models.DNSDomainRequest{}
	}
	err, added := retrieveModelDNSDomainRequestFlags(0, flagQueryModel, "request", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Query = flagQueryModel
	}

	if dryRun && debug {
		flagQueryValueDebugBytes, err := json.Marshal(m.Query)
		if err != nil {
			return err, false
		}
		logDebugf("Query dry-run payload: %v", string(flagQueryValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationDNSPostDNSSearchResult parses request result and return the string content
func parseOperationDNSPostDNSSearchResult(resp0 *dns.PostDomainSearchOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*dns.PostDNSSearchOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*dns.PostDNSSearchBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*dns.PostDNSSearchInternalServerError)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelPostDNSSearchOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded models.DNSAPIResponse flags

	if err := registerModelDNSAPIResponseFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	// register anonymous fields for postDnsSearchOKBodyAO1

	if err := registerPostDNSSearchOKBodyPropAnonPostDNSSearchOKBodyAO1Data(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostDNSSearchOKBodyPropAnonPostDNSSearchOKBodyAO1Pagination(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

// inline definition name postDnsSearchOKBodyAO1, type

func registerPostDNSSearchOKBodyPropAnonPostDNSSearchOKBodyAO1Data(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: data []string array type is not supported by go-swagger cli yet

	return nil
}

func registerPostDNSSearchOKBodyPropAnonPostDNSSearchOKBodyAO1Pagination(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagPaginationName string
	if cmdPrefix == "" {
		flagPaginationName = "pagination"
	} else {
		flagPaginationName = fmt.Sprintf("%v.pagination", cmdPrefix)
	}

	if err := registerModelDNSSearchPaginationFlags(depth+1, flagPaginationName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostDNSSearchOKBodyFlags(depth int, m *dns.PostDNSSearchOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model models.DNSAPIResponse
	err, PostDNSSearchOKBodyAO0Added := retrieveModelDNSAPIResponseFlags(depth, &m.DNSAPIResponse, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PostDNSSearchOKBodyAO0Added

	// retrieve allOf postDnsSearchOKBodyAO1 fields

	err, DataAdded := retrievePostDNSSearchOKBodyPropAnonPostDNSSearchOKBodyAO1DataFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DataAdded

	err, PaginationAdded := retrievePostDNSSearchOKBodyPropAnonPostDNSSearchOKBodyAO1PaginationFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PaginationAdded

	return nil, retAdded
}

// define retrieve functions for fields for inline definition name postDnsSearchOKBodyAO1

func retrievePostDNSSearchOKBodyPropAnonPostDNSSearchOKBodyAO1DataFlags(depth int, m *dns.PostDNSSearchOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDataName := fmt.Sprintf("%v.data", cmdPrefix)
	if cmd.Flags().Changed(flagDataName) {
		// warning: data array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrievePostDNSSearchOKBodyPropAnonPostDNSSearchOKBodyAO1PaginationFlags(depth int, m *dns.PostDNSSearchOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPaginationName := fmt.Sprintf("%v.pagination", cmdPrefix)
	if cmd.Flags().Changed(flagPaginationName) {
		// info: complex object pagination models.DNSSearchPagination is retrieved outside this Changed() block
	}
	flagPaginationValue := m.Pagination
	if swag.IsZero(flagPaginationValue) {
		flagPaginationValue = &models.DNSSearchPagination{}
	}

	err, PaginationAdded := retrieveModelDNSSearchPaginationFlags(depth+1, flagPaginationValue, flagPaginationName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PaginationAdded
	if PaginationAdded {
		m.Pagination = flagPaginationValue
	}

	return nil, retAdded
}
