// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/cybledev/odin-cli/models"
	"github.com/cybledev/odin-cli/odin_cli/hosts"

	"github.com/cybledev/odin-cli/decorator"
	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationHostsPostHostsFilteredSearchCmd returns a command to handle operation postHostsFilteredSearch
func makeOperationHostsPostHostsFilteredSearchCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Args:  cobra.NoArgs,
		Use:   "filtered-search",
		Short: `Returns the record based on query and blank query will return all records.`,
		RunE:  decorator.RunEColorWrapper(runOperationHostsPostHostsFilteredSearch),
	}

	if err := registerOperationHostsPostHostsFilteredSearchParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationHostsPostHostsFilteredSearch uses cmd flags to call endpoint api
func runOperationHostsPostHostsFilteredSearch(cmd *cobra.Command, args []string) (string, error) {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return "", err
	}
	// retrieve flag values from cmd and fill params
	params := hosts.NewPostHostsFilteredSearchParams()
	if err, _ = retrieveOperationHostsPostHostsFilteredSearchQueryFlag(params, "", cmd); err != nil {
		return "", err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return "", nil
	}
	// make request and then print result
	msgStr, err := parseOperationHostsPostHostsFilteredSearchResult(appCli.Hosts.PostHostsFilteredSearch(params, nil))
	if err != nil {
		return "", err
	}

	if !debug {
		return msgStr, nil
	}

	return "", nil
}

// registerOperationHostsPostHostsFilteredSearchParamFlags registers all flags needed to fill params
func registerOperationHostsPostHostsFilteredSearchParamFlags(cmd *cobra.Command) error {
	if err := registerOperationHostsPostHostsFilteredSearchQueryParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationHostsPostHostsFilteredSearchQueryParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagQueryName string
	if cmdPrefix == "" {
		flagQueryName = "query"
	} else {
		flagQueryName = fmt.Sprintf("%v.query", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagQueryName, "", `Optional json string for [query]. Search Query`)

	// add flags for body
	if err := registerModelIpservicesSearchRequestFlags(0, "request", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationHostsPostHostsFilteredSearchQueryFlag(m *hosts.PostHostsFilteredSearchParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("query") {
		// Read query string from cmd and unmarshal
		flagQueryValueStr, err := cmd.Flags().GetString("query")
		if err != nil {
			return err, false
		}

		flagQueryValue := models.IpservicesSearchRequest{}
		if err := json.Unmarshal([]byte(flagQueryValueStr), &flagQueryValue); err != nil {
			return fmt.Errorf("cannot unmarshal query string in models.IpservicesSearchRequest: %v", err), false
		}
		m.Query = &flagQueryValue
	}
	flagQueryModel := m.Query
	if swag.IsZero(flagQueryModel) {
		flagQueryModel = &models.IpservicesSearchRequest{}
	}
	err, added := retrieveModelIpservicesSearchRequestFlags(0, flagQueryModel, "request", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Query = flagQueryModel
	}

	if dryRun && debug {
		flagQueryValueDebugBytes, err := json.Marshal(m.Query)
		if err != nil {
			return err, false
		}
		logDebugf("Query dry-run payload: %v", string(flagQueryValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationHostsPostHostsFilteredSearchResult parses request result and return the string content
func parseOperationHostsPostHostsFilteredSearchResult(resp0 *hosts.PostHostsFilteredSearchOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*hosts.PostHostsFilteredSearchOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*hosts.PostHostsFilteredSearchBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp2 interface{} = respErr
		resp2, ok := iResp2.(*hosts.PostHostsFilteredSearchRequestTimeout)
		if ok {
			if !swag.IsZero(resp2) && !swag.IsZero(resp2.Payload) {
				msgStr, err := json.Marshal(resp2.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp3 interface{} = respErr
		resp3, ok := iResp3.(*hosts.PostHostsFilteredSearchInternalServerError)
		if ok {
			if !swag.IsZero(resp3) && !swag.IsZero(resp3.Payload) {
				msgStr, err := json.Marshal(resp3.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}

// register flags to command
func registerModelPostHostsFilteredSearchOKBodyFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	// register embedded models.IpservicesAPIResponse flags

	if err := registerModelIpservicesAPIResponseFlags(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	// register anonymous fields for postHostsFilteredSearchOKBodyAO1

	if err := registerPostHostsFilteredSearchOKBodyPropAnonPostHostsFilteredSearchOKBodyAO1Data(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPostHostsFilteredSearchOKBodyPropAnonPostHostsFilteredSearchOKBodyAO1Pagination(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

// inline definition name postHostsFilteredSearchOKBodyAO1, type

func registerPostHostsFilteredSearchOKBodyPropAnonPostHostsFilteredSearchOKBodyAO1Data(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: data []interface{} array type is not supported by go-swagger cli yet

	return nil
}

func registerPostHostsFilteredSearchOKBodyPropAnonPostHostsFilteredSearchOKBodyAO1Pagination(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	var flagPaginationName string
	if cmdPrefix == "" {
		flagPaginationName = "pagination"
	} else {
		flagPaginationName = fmt.Sprintf("%v.pagination", cmdPrefix)
	}

	if err := registerModelIpservicesSearchPaginationFlags(depth+1, flagPaginationName, cmd); err != nil {
		return err
	}

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPostHostsFilteredSearchOKBodyFlags(depth int, m *hosts.PostHostsFilteredSearchOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// retrieve model models.IpservicesAPIResponse
	err, PostHostsFilteredSearchOKBodyAO0Added := retrieveModelIpservicesAPIResponseFlags(depth, &m.IpservicesAPIResponse, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PostHostsFilteredSearchOKBodyAO0Added

	// retrieve allOf postHostsFilteredSearchOKBodyAO1 fields

	err, DataAdded := retrievePostHostsFilteredSearchOKBodyPropAnonPostHostsFilteredSearchOKBodyAO1DataFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || DataAdded

	err, PaginationAdded := retrievePostHostsFilteredSearchOKBodyPropAnonPostHostsFilteredSearchOKBodyAO1PaginationFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PaginationAdded

	return nil, retAdded
}

// define retrieve functions for fields for inline definition name postHostsFilteredSearchOKBodyAO1

func retrievePostHostsFilteredSearchOKBodyPropAnonPostHostsFilteredSearchOKBodyAO1DataFlags(depth int, m *hosts.PostHostsFilteredSearchOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagDataName := fmt.Sprintf("%v.data", cmdPrefix)
	if cmd.Flags().Changed(flagDataName) {
		// warning: data array type []interface{} is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrievePostHostsFilteredSearchOKBodyPropAnonPostHostsFilteredSearchOKBodyAO1PaginationFlags(depth int, m *hosts.PostHostsFilteredSearchOKBody, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPaginationName := fmt.Sprintf("%v.pagination", cmdPrefix)
	if cmd.Flags().Changed(flagPaginationName) {
		// info: complex object pagination models.IpservicesSearchPagination is retrieved outside this Changed() block
	}
	flagPaginationValue := m.Pagination
	if swag.IsZero(flagPaginationValue) {
		flagPaginationValue = &models.IpservicesSearchPagination{}
	}

	err, PaginationAdded := retrieveModelIpservicesSearchPaginationFlags(depth+1, flagPaginationValue, flagPaginationName, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PaginationAdded
	if PaginationAdded {
		m.Pagination = flagPaginationValue
	}

	return nil, retAdded
}
