// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/cybledev/odin-cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for SearchRequest

// register flags to command
func registerModelSearchRequestFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerSearchRequestPropLimit(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSearchRequestPropQuery(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerSearchRequestPropStart(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerSearchRequestPropLimit(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagLimitDescription := `Required. `

	var flagLimitName string
	if cmdPrefix == "" {
		flagLimitName = "limit"
	} else {
		flagLimitName = fmt.Sprintf("%v.limit", cmdPrefix)
	}

	var flagLimitDefault int64

	_ = cmd.PersistentFlags().Int64(flagLimitName, flagLimitDefault, flagLimitDescription)

	return nil
}

func registerSearchRequestPropQuery(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagQueryDescription := ``

	var flagQueryName string
	if cmdPrefix == "" {
		flagQueryName = "query"
	} else {
		flagQueryName = fmt.Sprintf("%v.query", cmdPrefix)
	}

	var flagQueryDefault string

	_ = cmd.PersistentFlags().String(flagQueryName, flagQueryDefault, flagQueryDescription)

	return nil
}

func registerSearchRequestPropStart(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: start []float64 array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSearchRequestFlags(depth int, m *models.SearchRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, LimitAdded := retrieveSearchRequestPropLimitFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || LimitAdded

	err, QueryAdded := retrieveSearchRequestPropQueryFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || QueryAdded

	err, StartAdded := retrieveSearchRequestPropStartFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || StartAdded

	return nil, retAdded
}

func retrieveSearchRequestPropLimitFlags(depth int, m *models.SearchRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagLimitName := fmt.Sprintf("%v.limit", cmdPrefix)
	if cmd.Flags().Changed(flagLimitName) {

		var flagLimitName string
		if cmdPrefix == "" {
			flagLimitName = "limit"
		} else {
			flagLimitName = fmt.Sprintf("%v.limit", cmdPrefix)
		}

		flagLimitValue, err := cmd.Flags().GetInt64(flagLimitName)
		if err != nil {
			return err, false
		}
		m.Limit = &flagLimitValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSearchRequestPropQueryFlags(depth int, m *models.SearchRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagQueryName := fmt.Sprintf("%v.query", cmdPrefix)
	if cmd.Flags().Changed(flagQueryName) {

		var flagQueryName string
		if cmdPrefix == "" {
			flagQueryName = "query"
		} else {
			flagQueryName = fmt.Sprintf("%v.query", cmdPrefix)
		}

		flagQueryValue, err := cmd.Flags().GetString(flagQueryName)
		if err != nil {
			return err, false
		}
		m.Query = flagQueryValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveSearchRequestPropStartFlags(depth int, m *models.SearchRequest, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagStartName := fmt.Sprintf("%v.start", cmdPrefix)
	if cmd.Flags().Changed(flagStartName) {
		// warning: start array type []float64 is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
