// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/cybledev/odin-cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for ServiceEncoding

// register flags to command
func registerModelServiceEncodingFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerServiceEncodingPropRaw(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerServiceEncodingPropRaw(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagRawDescription := ``

	var flagRawName string
	if cmdPrefix == "" {
		flagRawName = "raw"
	} else {
		flagRawName = fmt.Sprintf("%v.raw", cmdPrefix)
	}

	var flagRawDefault string

	_ = cmd.PersistentFlags().String(flagRawName, flagRawDefault, flagRawDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelServiceEncodingFlags(depth int, m *models.ServiceEncoding, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, RawAdded := retrieveServiceEncodingPropRawFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || RawAdded

	return nil, retAdded
}

func retrieveServiceEncodingPropRawFlags(depth int, m *models.ServiceEncoding, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagRawName := fmt.Sprintf("%v.raw", cmdPrefix)
	if cmd.Flags().Changed(flagRawName) {

		var flagRawName string
		if cmdPrefix == "" {
			flagRawName = "raw"
		} else {
			flagRawName = fmt.Sprintf("%v.raw", cmdPrefix)
		}

		flagRawValue, err := cmd.Flags().GetString(flagRawName)
		if err != nil {
			return err, false
		}
		m.Raw = flagRawValue

		retAdded = true
	}

	return nil, retAdded
}
