// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/cybledev/odin-cli/models"
	"github.com/spf13/cobra"
)

// Schema cli for TokensFinalStats

// register flags to command
func registerModelTokensFinalStatsFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerTokensFinalStatsPropLeft(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerTokensFinalStatsPropPlan(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerTokensFinalStatsPropLeft(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagLeftDescription := ``

	var flagLeftName string
	if cmdPrefix == "" {
		flagLeftName = "left"
	} else {
		flagLeftName = fmt.Sprintf("%v.left", cmdPrefix)
	}

	var flagLeftDefault int64

	_ = cmd.PersistentFlags().Int64(flagLeftName, flagLeftDefault, flagLeftDescription)

	return nil
}

func registerTokensFinalStatsPropPlan(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	flagPlanDescription := ``

	var flagPlanName string
	if cmdPrefix == "" {
		flagPlanName = "plan"
	} else {
		flagPlanName = fmt.Sprintf("%v.plan", cmdPrefix)
	}

	var flagPlanDefault int64

	_ = cmd.PersistentFlags().Int64(flagPlanName, flagPlanDefault, flagPlanDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelTokensFinalStatsFlags(depth int, m *models.TokensFinalStats, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, LeftAdded := retrieveTokensFinalStatsPropLeftFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || LeftAdded

	err, PlanAdded := retrieveTokensFinalStatsPropPlanFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || PlanAdded

	return nil, retAdded
}

func retrieveTokensFinalStatsPropLeftFlags(depth int, m *models.TokensFinalStats, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagLeftName := fmt.Sprintf("%v.left", cmdPrefix)
	if cmd.Flags().Changed(flagLeftName) {

		var flagLeftName string
		if cmdPrefix == "" {
			flagLeftName = "left"
		} else {
			flagLeftName = fmt.Sprintf("%v.left", cmdPrefix)
		}

		flagLeftValue, err := cmd.Flags().GetInt64(flagLeftName)
		if err != nil {
			return err, false
		}
		m.Left = flagLeftValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveTokensFinalStatsPropPlanFlags(depth int, m *models.TokensFinalStats, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	flagPlanName := fmt.Sprintf("%v.plan", cmdPrefix)
	if cmd.Flags().Changed(flagPlanName) {

		var flagPlanName string
		if cmdPrefix == "" {
			flagPlanName = "plan"
		} else {
			flagPlanName = fmt.Sprintf("%v.plan", cmdPrefix)
		}

		flagPlanValue, err := cmd.Flags().GetInt64(flagPlanName)
		if err != nil {
			return err, false
		}
		m.Plan = flagPlanValue

		retAdded = true
	}

	return nil, retAdded
}
