// Code generated by go-swagger; DO NOT EDIT.

package certificate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-cli/models"
)

// NewPostCertificatesCountParams creates a new PostCertificatesCountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCertificatesCountParams() *PostCertificatesCountParams {
	return &PostCertificatesCountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCertificatesCountParamsWithTimeout creates a new PostCertificatesCountParams object
// with the ability to set a timeout on a request.
func NewPostCertificatesCountParamsWithTimeout(timeout time.Duration) *PostCertificatesCountParams {
	return &PostCertificatesCountParams{
		timeout: timeout,
	}
}

// NewPostCertificatesCountParamsWithContext creates a new PostCertificatesCountParams object
// with the ability to set a context for a request.
func NewPostCertificatesCountParamsWithContext(ctx context.Context) *PostCertificatesCountParams {
	return &PostCertificatesCountParams{
		Context: ctx,
	}
}

// NewPostCertificatesCountParamsWithHTTPClient creates a new PostCertificatesCountParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCertificatesCountParamsWithHTTPClient(client *http.Client) *PostCertificatesCountParams {
	return &PostCertificatesCountParams{
		HTTPClient: client,
	}
}

/*
PostCertificatesCountParams contains all the parameters to send to the API endpoint

	for the post certificates count operation.

	Typically these are written to a http.Request.
*/
type PostCertificatesCountParams struct {

	/* Query.

	   Count Query
	*/
	Query *models.CertificateCertCountRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post certificates count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCertificatesCountParams) WithDefaults() *PostCertificatesCountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post certificates count params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCertificatesCountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post certificates count params
func (o *PostCertificatesCountParams) WithTimeout(timeout time.Duration) *PostCertificatesCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post certificates count params
func (o *PostCertificatesCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post certificates count params
func (o *PostCertificatesCountParams) WithContext(ctx context.Context) *PostCertificatesCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post certificates count params
func (o *PostCertificatesCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post certificates count params
func (o *PostCertificatesCountParams) WithHTTPClient(client *http.Client) *PostCertificatesCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post certificates count params
func (o *PostCertificatesCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuery adds the query to the post certificates count params
func (o *PostCertificatesCountParams) WithQuery(query *models.CertificateCertCountRequest) *PostCertificatesCountParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the post certificates count params
func (o *PostCertificatesCountParams) SetQuery(query *models.CertificateCertCountRequest) {
	o.Query = query
}

// WriteToRequest writes these params to a swagger request
func (o *PostCertificatesCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Query != nil {
		if err := r.SetBodyParam(o.Query); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
