// Code generated by go-swagger; DO NOT EDIT.

package exposed_files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cybledev/odin-cli/models"
)

// PostExposedFilesSearchReader is a Reader for the PostExposedFilesSearch structure.
type PostExposedFilesSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostExposedFilesSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostExposedFilesSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400,402,401:
		result := NewPostExposedFilesSearchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostExposedFilesSearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /exposed/files/search] PostExposedFilesSearch", response, response.Code())
	}
}

// NewPostExposedFilesSearchOK creates a PostExposedFilesSearchOK with default headers values
func NewPostExposedFilesSearchOK() *PostExposedFilesSearchOK {
	return &PostExposedFilesSearchOK{}
}

/*
PostExposedFilesSearchOK describes a response with status code 200, with default header values.

OK
*/
type PostExposedFilesSearchOK struct {
	Payload *models.ExposedFileAPIResponse
}

// IsSuccess returns true when this post exposed files search o k response has a 2xx status code
func (o *PostExposedFilesSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post exposed files search o k response has a 3xx status code
func (o *PostExposedFilesSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post exposed files search o k response has a 4xx status code
func (o *PostExposedFilesSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post exposed files search o k response has a 5xx status code
func (o *PostExposedFilesSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post exposed files search o k response a status code equal to that given
func (o *PostExposedFilesSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post exposed files search o k response
func (o *PostExposedFilesSearchOK) Code() int {
	return 200
}

func (o *PostExposedFilesSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /exposed/files/search][%d] postExposedFilesSearchOK %s", 200, payload)
}

func (o *PostExposedFilesSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /exposed/files/search][%d] postExposedFilesSearchOK %s", 200, payload)
}

func (o *PostExposedFilesSearchOK) GetPayload() *models.ExposedFileAPIResponse {
	return o.Payload
}

func (o *PostExposedFilesSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExposedFileAPIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostExposedFilesSearchBadRequest creates a PostExposedFilesSearchBadRequest with default headers values
func NewPostExposedFilesSearchBadRequest() *PostExposedFilesSearchBadRequest {
	return &PostExposedFilesSearchBadRequest{}
}

/*
PostExposedFilesSearchBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostExposedFilesSearchBadRequest struct {
	Payload interface{}
}

// IsSuccess returns true when this post exposed files search bad request response has a 2xx status code
func (o *PostExposedFilesSearchBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post exposed files search bad request response has a 3xx status code
func (o *PostExposedFilesSearchBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post exposed files search bad request response has a 4xx status code
func (o *PostExposedFilesSearchBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post exposed files search bad request response has a 5xx status code
func (o *PostExposedFilesSearchBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post exposed files search bad request response a status code equal to that given
func (o *PostExposedFilesSearchBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post exposed files search bad request response
func (o *PostExposedFilesSearchBadRequest) Code() int {
	return 400
}

func (o *PostExposedFilesSearchBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /exposed/files/search][%d] postExposedFilesSearchBadRequest %s", 400, payload)
}

func (o *PostExposedFilesSearchBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /exposed/files/search][%d] postExposedFilesSearchBadRequest %s", 400, payload)
}

func (o *PostExposedFilesSearchBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *PostExposedFilesSearchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostExposedFilesSearchInternalServerError creates a PostExposedFilesSearchInternalServerError with default headers values
func NewPostExposedFilesSearchInternalServerError() *PostExposedFilesSearchInternalServerError {
	return &PostExposedFilesSearchInternalServerError{}
}

/*
PostExposedFilesSearchInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostExposedFilesSearchInternalServerError struct {
	Payload interface{}
}

// IsSuccess returns true when this post exposed files search internal server error response has a 2xx status code
func (o *PostExposedFilesSearchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post exposed files search internal server error response has a 3xx status code
func (o *PostExposedFilesSearchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post exposed files search internal server error response has a 4xx status code
func (o *PostExposedFilesSearchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post exposed files search internal server error response has a 5xx status code
func (o *PostExposedFilesSearchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post exposed files search internal server error response a status code equal to that given
func (o *PostExposedFilesSearchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post exposed files search internal server error response
func (o *PostExposedFilesSearchInternalServerError) Code() int {
	return 500
}

func (o *PostExposedFilesSearchInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /exposed/files/search][%d] postExposedFilesSearchInternalServerError %s", 500, payload)
}

func (o *PostExposedFilesSearchInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /exposed/files/search][%d] postExposedFilesSearchInternalServerError %s", 500, payload)
}

func (o *PostExposedFilesSearchInternalServerError) GetPayload() interface{} {
	return o.Payload
}

func (o *PostExposedFilesSearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
