// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CybleComOdinAPIControllersV2IpservicesSearchPagination cyble com odin api controllers v2 ipservices search pagination
//
// swagger:model cyble_com_odin_api_controllers_v2_ipservices.SearchPagination
type CybleComOdinAPIControllersV2IpservicesSearchPagination struct {

	// last
	Last []float64 `json:"last"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// start
	Start []float64 `json:"start"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this cyble com odin api controllers v2 ipservices search pagination
func (m *CybleComOdinAPIControllersV2IpservicesSearchPagination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cyble com odin api controllers v2 ipservices search pagination based on context it is used
func (m *CybleComOdinAPIControllersV2IpservicesSearchPagination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CybleComOdinAPIControllersV2IpservicesSearchPagination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CybleComOdinAPIControllersV2IpservicesSearchPagination) UnmarshalBinary(b []byte) error {
	var res CybleComOdinAPIControllersV2IpservicesSearchPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
