// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CybleComOdinAPIControllersV2IpservicesSearchRequest cyble com odin api controllers v2 ipservices search request
//
// swagger:model cyble_com_odin_api_controllers_v2_ipservices.SearchRequest
type CybleComOdinAPIControllersV2IpservicesSearchRequest struct {

	// limit
	// Required: true
	Limit *int64 `json:"limit"`

	// query
	Query string `json:"query,omitempty"`

	// start
	Start []float64 `json:"start"`
}

// Validate validates this cyble com odin api controllers v2 ipservices search request
func (m *CybleComOdinAPIControllersV2IpservicesSearchRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CybleComOdinAPIControllersV2IpservicesSearchRequest) validateLimit(formats strfmt.Registry) error {

	if err := validate.Required("limit", "body", m.Limit); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this cyble com odin api controllers v2 ipservices search request based on context it is used
func (m *CybleComOdinAPIControllersV2IpservicesSearchRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CybleComOdinAPIControllersV2IpservicesSearchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CybleComOdinAPIControllersV2IpservicesSearchRequest) UnmarshalBinary(b []byte) error {
	var res CybleComOdinAPIControllersV2IpservicesSearchRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
