// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CybleComOdinAPIControllersV2FieldsField cyble com odin api controllers v2 fields field
//
// swagger:model cyble_com_odin_api_controllers_v2_fields.Field
type CybleComOdinAPIControllersV2FieldsField struct {

	// category
	Category string `json:"category,omitempty"`

	// display category
	DisplayCategory string `json:"display_category,omitempty"`

	// requires user subscription upgrade to access
	IsLocked bool `json:"is_locked,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this cyble com odin api controllers v2 fields field
func (m *CybleComOdinAPIControllersV2FieldsField) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cyble com odin api controllers v2 fields field based on context it is used
func (m *CybleComOdinAPIControllersV2FieldsField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CybleComOdinAPIControllersV2FieldsField) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CybleComOdinAPIControllersV2FieldsField) UnmarshalBinary(b []byte) error {
	var res CybleComOdinAPIControllersV2FieldsField
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
