// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DNSDNSCountRequest dns DNS count request
//
// swagger:model dns.DNSCountRequest
type DNSDNSCountRequest struct {

	// domain
	// Required: true
	Domain string `json:"domain,omitempty"`

	Keyword string `json:"keyword,omitempty"`

	// published after
	PublishedAfter string `json:"publishedAfter,omitempty"`

	// published before
	PublishedBefore string `json:"publishedBefore,omitempty"`
}

// Validate validates this dns DNS count request
func (m *DNSDNSCountRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DNSDNSCountRequest) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this dns DNS count request based on context it is used
func (m *DNSDNSCountRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DNSDNSCountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DNSDNSCountRequest) UnmarshalBinary(b []byte) error {
	var res DNSDNSCountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
