// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DNSSearchPagination dns search pagination
//
// swagger:model dns.SearchPagination
type DNSSearchPagination struct {

	// last
	Last []float64 `json:"last"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// start
	Start []float64 `json:"start"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this dns search pagination
func (m *DNSSearchPagination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dns search pagination based on context it is used
func (m *DNSSearchPagination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DNSSearchPagination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DNSSearchPagination) UnmarshalBinary(b []byte) error {
	var res DNSSearchPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
