// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EshandlerDNS eshandler DNS
//
// swagger:model eshandler.DNS
type EshandlerDNS struct {

	// added at
	AddedAt string `json:"added_at,omitempty"`

	// domain
	Domain string `json:"domain,omitempty"`

	// ext dns name
	ExtDNSName *EshandlerEXTDNSName `json:"ext_dns_name,omitempty"`

	// subdomain
	Subdomain string `json:"subdomain,omitempty"`
}

// Validate validates this eshandler DNS
func (m *EshandlerDNS) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExtDNSName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EshandlerDNS) validateExtDNSName(formats strfmt.Registry) error {
	if swag.IsZero(m.ExtDNSName) { // not required
		return nil
	}

	if m.ExtDNSName != nil {
		if err := m.ExtDNSName.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ext_dns_name")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ext_dns_name")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this eshandler DNS based on the context it is used
func (m *EshandlerDNS) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExtDNSName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EshandlerDNS) contextValidateExtDNSName(ctx context.Context, formats strfmt.Registry) error {

	if m.ExtDNSName != nil {

		if swag.IsZero(m.ExtDNSName) { // not required
			return nil
		}

		if err := m.ExtDNSName.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ext_dns_name")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ext_dns_name")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EshandlerDNS) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EshandlerDNS) UnmarshalBinary(b []byte) error {
	var res EshandlerDNS
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
