// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExposedBucket exposed bucket
//
// swagger:model exposed.Bucket
type ExposedBucket struct {

	// age in days
	AgeInDays int64 `json:"age_in_days,omitempty"`

	// categories
	Categories []string `json:"categories"`

	// deleted
	Deleted bool `json:"deleted,omitempty"`

	// ef mod at
	EfModAt string `json:"ef_mod_at,omitempty"`

	// file cat count
	FileCatCount map[string]int64 `json:"file_cat_count,omitempty"`

	// files
	Files int64 `json:"files,omitempty"`

	// ins at
	InsAt string `json:"ins_at,omitempty"`

	// labels
	Labels []string `json:"labels"`

	// last found at
	LastFoundAt string `json:"last_found_at,omitempty"`

	// last open at
	LastOpenAt string `json:"last_open_at,omitempty"`

	// lf mod at
	LfModAt string `json:"lf_mod_at,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// new files
	NewFiles int64 `json:"new_files,omitempty"`

	// open
	Open bool `json:"open,omitempty"`

	// owner id
	OwnerID string `json:"owner_id,omitempty"`

	// prev scan at
	PrevScanAt string `json:"prev_scan_at,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// scan at
	ScanAt string `json:"scan_at,omitempty"`

	// sensitive files
	SensitiveFiles int64 `json:"sensitive_files,omitempty"`
}

// Validate validates this exposed bucket
func (m *ExposedBucket) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this exposed bucket based on context it is used
func (m *ExposedBucket) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExposedBucket) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExposedBucket) UnmarshalBinary(b []byte) error {
	var res ExposedBucket
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
