// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExposedAggregate exposed aggregate
//
// swagger:model exposed.Aggregate
type ExposedAggregate struct {

	// buckets
	Buckets []interface{} `json:"buckets"`

	// doc count error upper bound
	DocCountErrorUpperBound int64 `json:"doc_count_error_upper_bound,omitempty"`

	// sum other doc count
	SumOtherDocCount int64 `json:"sum_other_doc_count,omitempty"`
}

// Validate validates this exposed aggregate
func (m *ExposedAggregate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this exposed aggregate based on context it is used
func (m *ExposedAggregate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExposedAggregate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExposedAggregate) UnmarshalBinary(b []byte) error {
	var res ExposedAggregate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
