// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FieldsAPIResponse fields API response
//
// swagger:model fields.APIResponse
type FieldsAPIResponse struct {

	// data
	Data interface{} `json:"data,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// pagination
	Pagination interface{} `json:"pagination,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this fields API response
func (m *FieldsAPIResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this fields API response based on context it is used
func (m *FieldsAPIResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FieldsAPIResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FieldsAPIResponse) UnmarshalBinary(b []byte) error {
	var res FieldsAPIResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
