// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IPCVE IP c v e
//
// swagger:model IPCVE
type IPCVE struct {

	// exploit
	Exploit []*IPExploitDetails `json:"exploit"`

	// id
	ID string `json:"id,omitempty"`

	// references
	References []string `json:"references"`

	// score
	Score float64 `json:"score,omitempty"`

	// services
	Services []string `json:"services"`

	// severity
	Severity string `json:"severity,omitempty"`

	// summary
	Summary string `json:"summary,omitempty"`

	// vector string
	VectorString string `json:"vector_string,omitempty"`

	// weakness
	Weakness string `json:"weakness,omitempty"`
}

// Validate validates this IP c v e
func (m *IPCVE) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExploit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IPCVE) validateExploit(formats strfmt.Registry) error {
	if swag.IsZero(m.Exploit) { // not required
		return nil
	}

	for i := 0; i < len(m.Exploit); i++ {
		if swag.IsZero(m.Exploit[i]) { // not required
			continue
		}

		if m.Exploit[i] != nil {
			if err := m.Exploit[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("exploit" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("exploit" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this IP c v e based on the context it is used
func (m *IPCVE) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExploit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IPCVE) contextValidateExploit(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Exploit); i++ {

		if m.Exploit[i] != nil {

			if swag.IsZero(m.Exploit[i]) { // not required
				return nil
			}

			if err := m.Exploit[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("exploit" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("exploit" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IPCVE) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPCVE) UnmarshalBinary(b []byte) error {
	var res IPCVE
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
