// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IPServiceSoftware IP service software
//
// swagger:model IPServiceSoftware
type IPServiceSoftware struct {

	// edition
	Edition interface{} `json:"edition,omitempty"`

	// language
	Language interface{} `json:"language,omitempty"`

	// part
	Part interface{} `json:"part,omitempty"`

	// product
	Product interface{} `json:"product,omitempty"`

	// update
	Update interface{} `json:"update,omitempty"`

	// uri
	URI string `json:"uri,omitempty"`

	// vendor
	Vendor interface{} `json:"vendor,omitempty"`

	// version
	Version interface{} `json:"version,omitempty"`
}

// Validate validates this IP service software
func (m *IPServiceSoftware) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this IP service software based on context it is used
func (m *IPServiceSoftware) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPServiceSoftware) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPServiceSoftware) UnmarshalBinary(b []byte) error {
	var res IPServiceSoftware
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
