// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IPServiceMeta IP service meta
//
// swagger:model IPServiceMeta
type IPServiceMeta struct {

	// category
	Category string `json:"category,omitempty"`

	// desc
	Desc string `json:"desc,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// tags
	Tags []string `json:"tags"`
}

// Validate validates this IP service meta
func (m *IPServiceMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this IP service meta based on context it is used
func (m *IPServiceMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IPServiceMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPServiceMeta) UnmarshalBinary(b []byte) error {
	var res IPServiceMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
