// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchemaAudit schema audit
//
// swagger:model schema.Audit
type SchemaAudit struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// expires date
	ExpiresDate string `json:"expires_date,omitempty"`

	// is audit logic applied (update in dates to fix invalid values)
	IsModified bool `json:"is_modified,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this schema audit
func (m *SchemaAudit) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this schema audit based on context it is used
func (m *SchemaAudit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SchemaAudit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchemaAudit) UnmarshalBinary(b []byte) error {
	var res SchemaAudit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
