// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceIPLocation service IP location
//
// swagger:model service.IPLocation
type ServiceIPLocation struct {

	// city
	City string `json:"city,omitempty"`

	// continent
	Continent string `json:"continent,omitempty"`

	// coordinates
	Coordinates *ServiceCoordinates `json:"coordinates,omitempty"`

	// country code
	CountryCode string `json:"country_code,omitempty"`

	// country name
	CountryName string `json:"country_name,omitempty"`

	// geo point
	GeoPoint string `json:"geo_point,omitempty"`

	// locale code
	LocaleCode string `json:"locale_code,omitempty"`

	// network
	Network string `json:"network,omitempty"`

	// postal code
	PostalCode string `json:"postal_code,omitempty"`
}

// Validate validates this service IP location
func (m *ServiceIPLocation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoordinates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceIPLocation) validateCoordinates(formats strfmt.Registry) error {
	if swag.IsZero(m.Coordinates) { // not required
		return nil
	}

	if m.Coordinates != nil {
		if err := m.Coordinates.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coordinates")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("coordinates")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this service IP location based on the context it is used
func (m *ServiceIPLocation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCoordinates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceIPLocation) contextValidateCoordinates(ctx context.Context, formats strfmt.Registry) error {

	if m.Coordinates != nil {

		if swag.IsZero(m.Coordinates) { // not required
			return nil
		}

		if err := m.Coordinates.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coordinates")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("coordinates")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceIPLocation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceIPLocation) UnmarshalBinary(b []byte) error {
	var res ServiceIPLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
