// Code generated by go-swagger; DO NOT EDIT.

package fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFieldsExposedBucketsParams creates a new GetFieldsExposedBucketsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFieldsExposedBucketsParams() *GetFieldsExposedBucketsParams {
	return &GetFieldsExposedBucketsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFieldsExposedBucketsParamsWithTimeout creates a new GetFieldsExposedBucketsParams object
// with the ability to set a timeout on a request.
func NewGetFieldsExposedBucketsParamsWithTimeout(timeout time.Duration) *GetFieldsExposedBucketsParams {
	return &GetFieldsExposedBucketsParams{
		timeout: timeout,
	}
}

// NewGetFieldsExposedBucketsParamsWithContext creates a new GetFieldsExposedBucketsParams object
// with the ability to set a context for a request.
func NewGetFieldsExposedBucketsParamsWithContext(ctx context.Context) *GetFieldsExposedBucketsParams {
	return &GetFieldsExposedBucketsParams{
		Context: ctx,
	}
}

// NewGetFieldsExposedBucketsParamsWithHTTPClient creates a new GetFieldsExposedBucketsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFieldsExposedBucketsParamsWithHTTPClient(client *http.Client) *GetFieldsExposedBucketsParams {
	return &GetFieldsExposedBucketsParams{
		HTTPClient: client,
	}
}

/*
GetFieldsExposedBucketsParams contains all the parameters to send to the API endpoint

	for the get fields exposed buckets operation.

	Typically these are written to a http.Request.
*/
type GetFieldsExposedBucketsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get fields exposed buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFieldsExposedBucketsParams) WithDefaults() *GetFieldsExposedBucketsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get fields exposed buckets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFieldsExposedBucketsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get fields exposed buckets params
func (o *GetFieldsExposedBucketsParams) WithTimeout(timeout time.Duration) *GetFieldsExposedBucketsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fields exposed buckets params
func (o *GetFieldsExposedBucketsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fields exposed buckets params
func (o *GetFieldsExposedBucketsParams) WithContext(ctx context.Context) *GetFieldsExposedBucketsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fields exposed buckets params
func (o *GetFieldsExposedBucketsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fields exposed buckets params
func (o *GetFieldsExposedBucketsParams) WithHTTPClient(client *http.Client) *GetFieldsExposedBucketsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fields exposed buckets params
func (o *GetFieldsExposedBucketsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetFieldsExposedBucketsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
