// Code generated by go-swagger; DO NOT EDIT.

package fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFieldsCertificatesCategoryParams creates a new GetFieldsCertificatesCategoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFieldsCertificatesCategoryParams() *GetFieldsCertificatesCategoryParams {
	return &GetFieldsCertificatesCategoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFieldsCertificatesCategoryParamsWithTimeout creates a new GetFieldsCertificatesCategoryParams object
// with the ability to set a timeout on a request.
func NewGetFieldsCertificatesCategoryParamsWithTimeout(timeout time.Duration) *GetFieldsCertificatesCategoryParams {
	return &GetFieldsCertificatesCategoryParams{
		timeout: timeout,
	}
}

// NewGetFieldsCertificatesCategoryParamsWithContext creates a new GetFieldsCertificatesCategoryParams object
// with the ability to set a context for a request.
func NewGetFieldsCertificatesCategoryParamsWithContext(ctx context.Context) *GetFieldsCertificatesCategoryParams {
	return &GetFieldsCertificatesCategoryParams{
		Context: ctx,
	}
}

// NewGetFieldsCertificatesCategoryParamsWithHTTPClient creates a new GetFieldsCertificatesCategoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFieldsCertificatesCategoryParamsWithHTTPClient(client *http.Client) *GetFieldsCertificatesCategoryParams {
	return &GetFieldsCertificatesCategoryParams{
		HTTPClient: client,
	}
}

/*
GetFieldsCertificatesCategoryParams contains all the parameters to send to the API endpoint

	for the get fields certificates category operation.

	Typically these are written to a http.Request.
*/
type GetFieldsCertificatesCategoryParams struct {

	/* Category.

	   get the category
	*/
	Category string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get fields certificates category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFieldsCertificatesCategoryParams) WithDefaults() *GetFieldsCertificatesCategoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get fields certificates category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFieldsCertificatesCategoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get fields certificates category params
func (o *GetFieldsCertificatesCategoryParams) WithTimeout(timeout time.Duration) *GetFieldsCertificatesCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fields certificates category params
func (o *GetFieldsCertificatesCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fields certificates category params
func (o *GetFieldsCertificatesCategoryParams) WithContext(ctx context.Context) *GetFieldsCertificatesCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fields certificates category params
func (o *GetFieldsCertificatesCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fields certificates category params
func (o *GetFieldsCertificatesCategoryParams) WithHTTPClient(client *http.Client) *GetFieldsCertificatesCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fields certificates category params
func (o *GetFieldsCertificatesCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the get fields certificates category params
func (o *GetFieldsCertificatesCategoryParams) WithCategory(category string) *GetFieldsCertificatesCategoryParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the get fields certificates category params
func (o *GetFieldsCertificatesCategoryParams) SetCategory(category string) {
	o.Category = category
}

// WriteToRequest writes these params to a swagger request
func (o *GetFieldsCertificatesCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param category
	if err := r.SetPathParam("category", o.Category); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
