// Code generated by go-swagger; DO NOT EDIT.

package fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFieldsExposedFilesParams creates a new GetFieldsExposedFilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFieldsExposedFilesParams() *GetFieldsExposedFilesParams {
	return &GetFieldsExposedFilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFieldsExposedFilesParamsWithTimeout creates a new GetFieldsExposedFilesParams object
// with the ability to set a timeout on a request.
func NewGetFieldsExposedFilesParamsWithTimeout(timeout time.Duration) *GetFieldsExposedFilesParams {
	return &GetFieldsExposedFilesParams{
		timeout: timeout,
	}
}

// NewGetFieldsExposedFilesParamsWithContext creates a new GetFieldsExposedFilesParams object
// with the ability to set a context for a request.
func NewGetFieldsExposedFilesParamsWithContext(ctx context.Context) *GetFieldsExposedFilesParams {
	return &GetFieldsExposedFilesParams{
		Context: ctx,
	}
}

// NewGetFieldsExposedFilesParamsWithHTTPClient creates a new GetFieldsExposedFilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFieldsExposedFilesParamsWithHTTPClient(client *http.Client) *GetFieldsExposedFilesParams {
	return &GetFieldsExposedFilesParams{
		HTTPClient: client,
	}
}

/*
GetFieldsExposedFilesParams contains all the parameters to send to the API endpoint

	for the get fields exposed files operation.

	Typically these are written to a http.Request.
*/
type GetFieldsExposedFilesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get fields exposed files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFieldsExposedFilesParams) WithDefaults() *GetFieldsExposedFilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get fields exposed files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFieldsExposedFilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get fields exposed files params
func (o *GetFieldsExposedFilesParams) WithTimeout(timeout time.Duration) *GetFieldsExposedFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fields exposed files params
func (o *GetFieldsExposedFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fields exposed files params
func (o *GetFieldsExposedFilesParams) WithContext(ctx context.Context) *GetFieldsExposedFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fields exposed files params
func (o *GetFieldsExposedFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fields exposed files params
func (o *GetFieldsExposedFilesParams) WithHTTPClient(client *http.Client) *GetFieldsExposedFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fields exposed files params
func (o *GetFieldsExposedFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetFieldsExposedFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
