// Code generated by go-swagger; DO NOT EDIT.

package fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetExposedCategoryParams creates a new GetExposedCategoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetExposedCategoryParams() *GetExposedCategoryParams {
	return &GetExposedCategoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetExposedCategoryParamsWithTimeout creates a new GetExposedCategoryParams object
// with the ability to set a timeout on a request.
func NewGetExposedCategoryParamsWithTimeout(timeout time.Duration) *GetExposedCategoryParams {
	return &GetExposedCategoryParams{
		timeout: timeout,
	}
}

// NewGetExposedCategoryParamsWithContext creates a new GetExposedCategoryParams object
// with the ability to set a context for a request.
func NewGetExposedCategoryParamsWithContext(ctx context.Context) *GetExposedCategoryParams {
	return &GetExposedCategoryParams{
		Context: ctx,
	}
}

// NewGetExposedCategoryParamsWithHTTPClient creates a new GetExposedCategoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetExposedCategoryParamsWithHTTPClient(client *http.Client) *GetExposedCategoryParams {
	return &GetExposedCategoryParams{
		HTTPClient: client,
	}
}

/*
GetExposedCategoryParams contains all the parameters to send to the API endpoint

	for the get exposed category operation.

	Typically these are written to a http.Request.
*/
type GetExposedCategoryParams struct {

	/* Category.

	   get the category
	*/
	Category string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get exposed category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetExposedCategoryParams) WithDefaults() *GetExposedCategoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get exposed category params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetExposedCategoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get exposed category params
func (o *GetExposedCategoryParams) WithTimeout(timeout time.Duration) *GetExposedCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get exposed category params
func (o *GetExposedCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get exposed category params
func (o *GetExposedCategoryParams) WithContext(ctx context.Context) *GetExposedCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get exposed category params
func (o *GetExposedCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get exposed category params
func (o *GetExposedCategoryParams) WithHTTPClient(client *http.Client) *GetExposedCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get exposed category params
func (o *GetExposedCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the get exposed category params
func (o *GetExposedCategoryParams) WithCategory(category string) *GetExposedCategoryParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the get exposed category params
func (o *GetExposedCategoryParams) SetCategory(category string) {
	o.Category = category
}

// WriteToRequest writes these params to a swagger request
func (o *GetExposedCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param category
	if err := r.SetPathParam("category", o.Category); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
